### ISSUE TITLE
ASM_clust repository missing file

### ISSUE THREAD

**Issue by gjerman** [dspeth/bioinfo_scripts#1]
Please add the file bhtsne.py to the repository,  ASM_clust.sh will not run without it.

**Comment by dspeth** [comment]
Ah, I'm sorry I wasn't clear here. bhtsne.py is an external dependency, written by Laurens van der Maaten.
It can be downloaded and installed from here: https://github.com/lvdmaaten/bhtsne
I have  added this to the README file
